version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(deps)"
    groups:
      stryker:
        patterns:
          - "@stryker-mutator/*"
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"
      commitlint:
        patterns:
          - "@commitlint/*"
      salesforce:
        patterns:
          - "@salesforce/*"
          - "@oclif/*"
