coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

ignore:
  - "test"
  - "test/**/*"
  - "lib"
  - "lib/**/*"
  - "dist"
  - "dist/**/*"
  - "coverage"
  - "coverage/**/*"
  - "**/*.nut.ts"
  - "node_modules"
