on:
  workflow_call:
    inputs:
      os:
        required: false
        description: 'runs-on property, ex: ubuntu-latest, windows-latest'
        type: string
        default: 'ubuntu-latest'
      command:
        required: false
        type: string
        default: yarn test:nuts
        description: 'command to execute (ex: yarn test:nuts)'

jobs:
  nut:
    name: ${{ inputs.command }}
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Node
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 18
          cache: yarn
          registry-url: 'https://registry.npmjs.org'
          check-latest: true
          node-options: "--experimental-specifier-resolution=node"

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Install salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Clear Yarn Cache (Ubuntu)
        if: runner.os == 'Linux'
        run: yarn cache clean

      - name: Install plugin
        run: |
          sf plugins:link .
          sf plugins

      - name: Run NUT
        run: ${{ inputs.command }}
