name: tests
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

jobs:
  nuts:
    uses: ./.github/workflows/nut.yml
    secrets: inherit
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false
    with:
      os: ${{ matrix.os }}
